/*
 * Confluent Data Catalog
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.confluent.demo.datamesh.cc.datacatalog.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.confluent.demo.datamesh.cc.datacatalog.model.AtlasEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * AtlasEntityWithExtInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-05T12:27:07.994303-05:00[America/Chicago]")
public class AtlasEntityWithExtInfo {
  @SerializedName("referredEntities")
  private Map<String, AtlasEntity> referredEntities = null;

  @SerializedName("entity")
  private AtlasEntity entity = null;

  public AtlasEntityWithExtInfo referredEntities(Map<String, AtlasEntity> referredEntities) {
    this.referredEntities = referredEntities;
    return this;
  }

  public AtlasEntityWithExtInfo putReferredEntitiesItem(String key, AtlasEntity referredEntitiesItem) {
    if (this.referredEntities == null) {
      this.referredEntities = new HashMap<String, AtlasEntity>();
    }
    this.referredEntities.put(key, referredEntitiesItem);
    return this;
  }

   /**
   * Get referredEntities
   * @return referredEntities
  **/
  @Schema(description = "")
  public Map<String, AtlasEntity> getReferredEntities() {
    return referredEntities;
  }

  public void setReferredEntities(Map<String, AtlasEntity> referredEntities) {
    this.referredEntities = referredEntities;
  }

  public AtlasEntityWithExtInfo entity(AtlasEntity entity) {
    this.entity = entity;
    return this;
  }

   /**
   * Get entity
   * @return entity
  **/
  @Schema(description = "")
  public AtlasEntity getEntity() {
    return entity;
  }

  public void setEntity(AtlasEntity entity) {
    this.entity = entity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AtlasEntityWithExtInfo atlasEntityWithExtInfo = (AtlasEntityWithExtInfo) o;
    return Objects.equals(this.referredEntities, atlasEntityWithExtInfo.referredEntities) &&
        Objects.equals(this.entity, atlasEntityWithExtInfo.entity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referredEntities, entity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AtlasEntityWithExtInfo {\n");
    
    sb.append("    referredEntities: ").append(toIndentedString(referredEntities)).append("\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
