/*
 * Confluent Data Catalog
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.confluent.demo.datamesh.cc.datacatalog.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.confluent.demo.datamesh.cc.datacatalog.model.AtlasEntityHeader;
import io.confluent.demo.datamesh.cc.datacatalog.model.SearchParams;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * SearchResult
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-05T12:27:07.994303-05:00[America/Chicago]")
public class SearchResult {
  @SerializedName("searchParameters")
  private SearchParams searchParameters = null;

  @SerializedName("types")
  private List<String> types = null;

  @SerializedName("entities")
  private List<AtlasEntityHeader> entities = null;

  @SerializedName("referredEntities")
  private Map<String, AtlasEntityHeader> referredEntities = null;

  public SearchResult searchParameters(SearchParams searchParameters) {
    this.searchParameters = searchParameters;
    return this;
  }

   /**
   * Get searchParameters
   * @return searchParameters
  **/
  @Schema(description = "")
  public SearchParams getSearchParameters() {
    return searchParameters;
  }

  public void setSearchParameters(SearchParams searchParameters) {
    this.searchParameters = searchParameters;
  }

  public SearchResult types(List<String> types) {
    this.types = types;
    return this;
  }

  public SearchResult addTypesItem(String typesItem) {
    if (this.types == null) {
      this.types = new ArrayList<String>();
    }
    this.types.add(typesItem);
    return this;
  }

   /**
   * Get types
   * @return types
  **/
  @Schema(description = "")
  public List<String> getTypes() {
    return types;
  }

  public void setTypes(List<String> types) {
    this.types = types;
  }

  public SearchResult entities(List<AtlasEntityHeader> entities) {
    this.entities = entities;
    return this;
  }

  public SearchResult addEntitiesItem(AtlasEntityHeader entitiesItem) {
    if (this.entities == null) {
      this.entities = new ArrayList<AtlasEntityHeader>();
    }
    this.entities.add(entitiesItem);
    return this;
  }

   /**
   * Get entities
   * @return entities
  **/
  @Schema(description = "")
  public List<AtlasEntityHeader> getEntities() {
    return entities;
  }

  public void setEntities(List<AtlasEntityHeader> entities) {
    this.entities = entities;
  }

  public SearchResult referredEntities(Map<String, AtlasEntityHeader> referredEntities) {
    this.referredEntities = referredEntities;
    return this;
  }

  public SearchResult putReferredEntitiesItem(String key, AtlasEntityHeader referredEntitiesItem) {
    if (this.referredEntities == null) {
      this.referredEntities = new HashMap<String, AtlasEntityHeader>();
    }
    this.referredEntities.put(key, referredEntitiesItem);
    return this;
  }

   /**
   * Get referredEntities
   * @return referredEntities
  **/
  @Schema(description = "")
  public Map<String, AtlasEntityHeader> getReferredEntities() {
    return referredEntities;
  }

  public void setReferredEntities(Map<String, AtlasEntityHeader> referredEntities) {
    this.referredEntities = referredEntities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResult searchResult = (SearchResult) o;
    return Objects.equals(this.searchParameters, searchResult.searchParameters) &&
        Objects.equals(this.types, searchResult.types) &&
        Objects.equals(this.entities, searchResult.entities) &&
        Objects.equals(this.referredEntities, searchResult.referredEntities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(searchParameters, types, entities, referredEntities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResult {\n");
    
    sb.append("    searchParameters: ").append(toIndentedString(searchParameters)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    referredEntities: ").append(toIndentedString(referredEntities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
